In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
city  = pd.read_csv("data/processed/weather/city_catalog.csv")

In [4]:
city

            city         country      continent  latitude  longitude
0          Delhi           India           Asia   28.6139    77.2090
1          Tokyo           Japan           Asia   35.6762   139.6503
2      Singapore       Singapore           Asia    1.3521   103.8198
3         London  United Kingdom         Europe   51.5072    -0.1276
4          Paris          France         Europe   48.8566     2.3522
5         Berlin         Germany         Europe   52.5200    13.4050
6       New York             USA  North America   40.7128   -74.0060
7    Los Angeles             USA  North America   34.0522  -118.2437
8        Toronto          Canada  North America   43.6532   -79.3832
9      Sao Paulo          Brazil  South America  -23.5505   -46.6333
10  Buenos Aires       Argentina  South America  -34.6037   -58.3816
11         Cairo           Egypt         Africa   30.0444    31.2357
12       Nairobi           Kenya         Africa   -1.2921    36.8219
13     Cape Town    South Africa         Africa  -33.9249    18.4241
14        Sydney       Australia      Australia  -33.8688   151.2093

In [5]:
global_temp = pd.read_csv("data/processed/weather/global_temperature_dataset.csv")
global_temp.head()

,date,year,month,month_name,day,season,city,country,continent,latitude,...,temperature_2m_max,temperature_2m_min,city_mean_temperature,temperature_anomaly,rolling_7d_avg,rolling_30d_avg,data_source,continent_yearly_mean,city_yearly_mean,global_daily_mean
0,2015-01-01,2015,1,January,1,Winter,Cairo,Egypt,Africa,30.0444,...,15.5,7.9,23.197947,-10.897947,12.3,12.3,Open-Meteo Archive API,19.713425,22.526027,11.78
1,2015-01-01,2015,1,January,1,Winter,Cape Town,South Africa,Africa,-33.9249,...,25.0,18.7,17.003504,4.596496,21.6,21.6,Open-Meteo Archive API,19.713425,17.254795,11.78
2,2015-01-01,2015,1,January,1,Winter,Nairobi,Kenya,Africa,-1.2921,...,27.5,13.7,18.953737,1.546263,20.5,20.5,Open-Meteo Archive API,19.713425,19.359452,11.78
3,2015-01-01,2015,1,January,1,Winter,Delhi,India,Asia,28.6139,...,21.3,12.0,24.533206,-8.233206,16.3,16.3,Open-Meteo Archive API,22.042648,24.382466,11.78
4,2015-01-01,2015,1,January,1,Winter,Singapore,Singapore,Asia,1.3521,...,25.4,24.0,26.698796,-2.098796,24.6,24.6,Open-Meteo Archive API,22.042648,26.568493,11.78

In [6]:
global_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54795 entries, 0 to 54794
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   54795 non-null  object
 1   year                   54795 non-null  int64
 2   month                  54795 non-null  int64
 3   month_name             54795 non-null  object
 4   day                    54795 non-null  int64
 5   season                 54795 non-null  object
 6   city                   54795 non-null  object
 7   country                54795 non-null  object
 8   continent              54795 non-null  object
 9   latitude               54795 non-null  float64
 10  longitude              54795 non-null  float64
 11  temperature_2m_mean    54795 non-null  float64
 12  temperature_2m_max     54795 non-null  float64
 13  temperature_2m_min     54795 non-null  float64
 14  city_mean_temperature  54795 non-null  float64
 15  temperature_anomaly    54795 non-null  float64
 16  rolling_7d_avg         54795 non-null  float64
 17  rolling_30d_avg        54795 non-null  float64
 18  data_source            54795 non-null  object
 19  continent_yearly_mean  54795 non-null  float64
 20  city_yearly_mean       54795 non-null  float64
 21  global_daily_mean      54795 non-null  float64
dtypes: float64(12), int64(3), object(7)
memory usage: 9.2+ MB

In [7]:
global_temp = global_temp.drop(columns=["data_source", "year", "month", "month_name", "day"], axis=1)

In [8]:
global_temp.columns

Index(['date', 'season', 'city', 'country', 'continent', 'latitude',
       'longitude', 'temperature_2m_mean', 'temperature_2m_max',
       'temperature_2m_min', 'city_mean_temperature', 'temperature_anomaly',
       'rolling_7d_avg', 'rolling_30d_avg', 'continent_yearly_mean',
       'city_yearly_mean', 'global_daily_mean'],
      dtype='object')

In [9]:
global_temp.describe()

,latitude,longitude,temperature_2m_mean,temperature_2m_max,temperature_2m_min,city_mean_temperature,temperature_anomaly,rolling_7d_avg,rolling_30d_avg,continent_yearly_mean,city_yearly_mean,global_daily_mean
count,54795.00000,54795.000000,54795.000000,54795.000000,54795.000000,54795.000000,5.479500e+04,54795.000000,54795.000000,54795.000000,54795.000000,54795.000000
mean,15.98324,13.156793,17.011746,21.690755,12.889096,17.011746,-1.825795e-16,17.010708,17.007685,17.011746,17.011746,17.011746
std,32.39040,77.764952,7.982488,8.702766,7.835110,4.990506,6.230166e+00,7.766786,7.587666,4.026555,5.013515,3.118071
min,-34.60370,-118.243700,-21.500000,-17.400000,-25.100000,9.317602,-3.081760e+01,-15.928571,-11.910000,10.655982,8.156986,9.846667
25%,-23.55050,-58.381600,12.300000,16.300000,8.200000,12.333260,-3.851766e+00,12.471429,12.573333,13.165662,12.244658,14.226667
50%,30.04440,13.405000,17.900000,22.700000,13.600000,17.551766,4.626335e-02,17.928571,17.953333,18.293306,17.372951,17.213333
75%,43.65320,77.209000,22.400000,27.900000,18.000000,19.493184,4.066740e+00,22.100000,21.870000,19.873679,19.276986,19.933333
max,52.52000,151.209300,39.200000,46.300000,34.500000,26.698796,1.986674e+01,38.057143,36.916667,22.752823,27.012603,23.206667

In [10]:
global_temp["date"] = pd.to_datetime(global_temp["date"])

In [11]:
global_temp.head()

,date,season,city,country,continent,latitude,longitude,temperature_2m_mean,temperature_2m_max,temperature_2m_min,city_mean_temperature,temperature_anomaly,rolling_7d_avg,rolling_30d_avg,continent_yearly_mean,city_yearly_mean,global_daily_mean
0,2015-01-01,Winter,Cairo,Egypt,Africa,30.0444,31.2357,12.3,15.5,7.9,23.197947,-10.897947,12.3,12.3,19.713425,22.526027,11.78
1,2015-01-01,Winter,Cape Town,South Africa,Africa,-33.9249,18.4241,21.6,25.0,18.7,17.003504,4.596496,21.6,21.6,19.713425,17.254795,11.78
2,2015-01-01,Winter,Nairobi,Kenya,Africa,-1.2921,36.8219,20.5,27.5,13.7,18.953737,1.546263,20.5,20.5,19.713425,19.359452,11.78
3,2015-01-01,Winter,Delhi,India,Asia,28.6139,77.2090,16.3,21.3,12.0,24.533206,-8.233206,16.3,16.3,22.042648,24.382466,11.78
4,2015-01-01,Winter,Singapore,Singapore,Asia,1.3521,103.8198,24.6,25.4,24.0,26.698796,-2.098796,24.6,24.6,22.042648,26.568493,11.78

In [12]:
base_df = global_temp[
    [
        "city",
        "country",
        "continent",
        "latitude",
        "longitude",
        "date",
        "temperature_2m_mean",
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_anomaly"
    ]
].copy()

city_wise_full = base_df.pivot_table(
    index=["city", "country", "continent", "latitude", "longitude"],
    columns="date",
    values=[
        "temperature_2m_mean",
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_anomaly"
    ]
)

In [13]:
city_wise_full.shape

(15, 14612)

In [14]:
city_wise_full.columns = [
    f"{metric}_{date.strftime('%Y-%m-%d')}"
    for metric, date in city_wise_full.columns
]
city_wise_full = city_wise_full.reset_index()

In [15]:
city_wise_full.head()

,city,country,continent,latitude,longitude,temperature_2m_max_2015-01-01,temperature_2m_max_2015-01-02,temperature_2m_max_2015-01-03,temperature_2m_max_2015-01-04,temperature_2m_max_2015-01-05,...,temperature_anomaly_2024-12-22,temperature_anomaly_2024-12-23,temperature_anomaly_2024-12-24,temperature_anomaly_2024-12-25,temperature_anomaly_2024-12-26,temperature_anomaly_2024-12-27,temperature_anomaly_2024-12-28,temperature_anomaly_2024-12-29,temperature_anomaly_2024-12-30,temperature_anomaly_2024-12-31
0,Berlin,Germany,Europe,52.5200,13.4050,4.4,7.5,5.1,4.2,3.7,...,-5.484561,-7.684561,-7.484561,-8.584561,-5.584561,-7.284561,-12.084561,-11.884561,-8.384561,-9.184561
1,Buenos Aires,Argentina,South America,-34.6037,-58.3816,22.8,23.6,27.1,23.6,30.3,...,4.519956,7.419956,4.419956,0.819956,2.719956,4.719956,4.319956,4.619956,6.019956,7.519956
2,Cairo,Egypt,Africa,30.0444,31.2357,15.5,17.6,16.9,17.6,17.8,...,-6.797947,-7.397947,-8.597947,-7.897947,-9.997947,-9.897947,-9.397947,-8.797947,-9.297947,-8.797947
3,Cape Town,South Africa,Africa,-33.9249,18.4241,25.0,24.1,24.3,24.1,22.6,...,4.096496,2.996496,4.296496,7.996496,6.296496,3.596496,5.796496,2.596496,1.296496,1.896496
4,Delhi,India,Asia,28.6139,77.2090,21.3,17.2,17.9,19.1,20.7,...,-8.233206,-10.033206,-9.833206,-9.433206,-8.433206,-9.433206,-9.633206,-10.833206,-11.833206,-13.233206

In [16]:
city_wise_full.to_csv("data/processed/weather/city_wise_10yr_clean.csv", index=False)

In [17]:
city_wise_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Columns: 14617 entries, city to temperature_anomaly_2024-12-31
dtypes: float64(14614), object(3)
memory usage: 1.7+ MB

In [18]:
city_wise_full.describe()

,latitude,longitude,temperature_2m_max_2015-01-01,temperature_2m_max_2015-01-02,temperature_2m_max_2015-01-03,temperature_2m_max_2015-01-04,temperature_2m_max_2015-01-05,temperature_2m_max_2015-01-06,temperature_2m_max_2015-01-07,temperature_2m_max_2015-01-08,...,temperature_anomaly_2024-12-22,temperature_anomaly_2024-12-23,temperature_anomaly_2024-12-24,temperature_anomaly_2024-12-25,temperature_anomaly_2024-12-26,temperature_anomaly_2024-12-27,temperature_anomaly_2024-12-28,temperature_anomaly_2024-12-29,temperature_anomaly_2024-12-30,temperature_anomaly_2024-12-31
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,15.983240,13.156793,15.400000,16.680000,16.533333,17.473333,17.040000,16.593333,16.186667,16.086667,...,-4.865079,-4.631746,-4.058412,-3.798412,-3.971746,-4.151746,-4.045079,-3.698412,-3.305079,-3.551746
std,33.526943,80.493639,11.098713,9.884129,9.750214,9.414386,10.657244,12.608130,13.084935,12.370464,...,8.298804,7.760415,5.871817,6.532177,6.556606,6.993698,6.425751,5.922683,5.685291,6.225166
min,-34.603700,-118.243700,-1.600000,-0.600000,2.000000,3.500000,-2.200000,-6.700000,-8.000000,-8.400000,...,-22.117602,-22.712456,-14.212456,-15.412456,-17.512456,-16.312456,-12.084561,-11.884561,-11.833206,-13.233206
25%,-12.421300,-52.507450,4.550000,8.750000,6.850000,9.150000,8.250000,7.750000,6.400000,9.550000,...,-7.515576,-8.858883,-8.957774,-8.953271,-8.177594,-9.277594,-9.515576,-9.215604,-8.658910,-8.765604
50%,30.044400,13.405000,15.500000,17.200000,16.900000,19.100000,20.700000,20.600000,18.100000,19.600000,...,-5.484561,-6.135067,-4.859075,-2.933260,-5.233260,-6.059075,-5.935067,-4.217602,-4.035067,-6.312456
75%,42.183000,57.015450,25.200000,25.300000,26.000000,24.800000,25.050000,27.900000,27.300000,26.650000,...,1.054010,0.676540,0.626540,0.233110,0.826540,1.076540,1.626540,1.676540,1.321380,1.521380
max,52.520000,151.209300,31.400000,30.800000,29.100000,30.200000,30.300000,29.800000,30.200000,30.000000,...,4.648234,7.419956,4.419956,7.996496,6.296496,8.848234,5.796496,4.848234,6.019956,7.519956